- name: CONFIG IPv4 IP ADDRESS OBJECT
  hosts: DC-MGT-Forti-CNI-FMG-21
  connection: httpapi
  gather_facts: False

  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443

  tasks:
    - name: Configure IPv4 addresses.
      fmgr_fwobj_address:
        bypass_validation: False
        adom: root
        state: present
        firewall_address:
           allow-routing: disable
           associated-interface: any
           name: 'address-orignal'
           visibility: enable
