- name: CONFIG IPv4 IP ADDRESS OBJECT
  hosts: DC-MGT-Forti-CNI-FMG-21
  connection: httpapi
  gather_facts: False

  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443

  tasks:
  - name: ADD IPv4 IP ADDRESS OBJECT
    fmgr_fwobj_address:
      mode: "add"
      adom: "root"
      ipv4: "ipmask"
      ipv4addr: "10.7.220.30/32"
      name: "ansible_v4Obj_ipMask2"
      comment: "Ansible is SUCKS! Paramgram!"
      #tags: "ansible, ipv4, object"
      color: "26"
